AppBundle\Entity\Pays: ~
AppBundle\Entity\Langage: ~

AppBundle\Entity\Ville: ~
AppBundle\Entity\FichierCode: ~

AppBundle\Entity\EntreeSortie:
    attributes:
        normalization_context:
            groups: [es-read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\TypeEntreeSortie:
    attributes:
        normalization_context:
            groups: [type-es-read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\Solution:
    collectionOperations:
        get:
            method: GET

AppBundle\Entity\Probleme:
    attributes:
        normalization_context:
            groups: [prob-read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\TypeParticipation:
    attributes:
        normalization_context:
            groups: [type-particip-read, brief]
        denormalization_context:
            groups: [write]

AppBundle\Entity\Participation:
    attributes:
        normalization_context:
            groups:
                - particip-read
                - brief
        denormalization_context:
            groups:
                - write
        filters:
            - invit_participation.accepte
            - participation.type_filter

AppBundle\Entity\Utilisateur:
    attributes:
        normalization_context: 
            groups: [read]
        denormalization_context: 
            groups: [write]
        filters: [utilisateur.username_filter]

AppBundle\Entity\Admin:
    attributes:
        normalization_context: 
            groups: [read]
        denormalization_context: 
            groups: [write] 

AppBundle\Entity\Membre:
    attributes:
        normalization_context:
            groups: [read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\Organisateur:
    attributes:
       normalization_context: 
            groups: [read, org] 
       denormalization_context: 
            groups: [write] 

AppBundle\Entity\Participant:
    attributes:
        normalization_context:
            groups: [read, particip-invit-read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\Competition:
    attributes:
        normalization_context:
            groups: [brief, comp-read]
        filters:
            - competition.public
            - competition.publie
            - competition.tempsDebut
            - competition.tempsFin
            - competition.titre_filter
            - competition.langages_filter