AppBundle\Entity\Pays: ~
AppBundle\Entity\Langage: ~
AppBundle\Entity\Probleme: ~
AppBundle\Entity\EntreeSortie: ~
AppBundle\Entity\TypeEntreeSortie: ~
AppBundle\Entity\Ville: ~
AppBundle\Entity\FichierCode: ~
AppBundle\Entity\Solution:
    collectionOperations:
        get:
            method: GET

AppBundle\Entity\Utilisateur:
    attributes:
        normalization_context: 
            groups: [read]
        denormalization_context: 
            groups: [write]
        filters: [utilisateur.username_filter]

AppBundle\Entity\Admin:
    attributes:
        normalization_context: 
            groups: [read]
        denormalization_context: 
            groups: [write] 

AppBundle\Entity\Membre:
    attributes:
        normalization_context:
            groups: [read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\Organisateur:
    attributes:
       normalization_context: 
            groups: [read, org] 
       denormalization_context: 
            groups: [write] 

AppBundle\Entity\Participant:
    attributes:
        normalization_context:
            groups: [read, particip-invit-read]
        denormalization_context:
            groups: [write]

AppBundle\Entity\Competition:
    attributes:
        normalization_context:
            groups: [brief, comp-read]
        filters:
            - competition.public
            - competition.publie
            - competition.tempsDebut
            - competition.tempsFin
            - competition.titre_filter
            - competition.langages_filter

AppBundle\Entity\InvitParticipation:
    filters: [invit_participation.accepte]

AppBundle\Entity\DemandeParticipation:
    filters: [invit_participation.accepte]