# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: webplates/symfony-php

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer install
          - chmod +x create-test-db.sh
          - ./create-test-db.sh
          - composer test