# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ybouhjira/php

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - cp app/config/parameters.yml.dist app/config/parameters.yml
          - mkdir -p var/jwt 
          - openssl genrsa -passout pass:password -out var/jwt/private.pem -aes256 4096
          - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem
          - composer install
          - chmod +x create-test-db.sh
          - ./create-test-db.sh
          - composer test
