imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

api_platform:
    title: 'Compétition de programmation'
    description: 'Platforme de compétitions'
    version: '0.1.0'
    enable_fos_user: true
    collection:
        pagination:
            enabled: true
            client_enabled: false
            client_items_per_page: true
            items_per_page: 10
            maximum_items_per_page: 30
            page_parameter_name: 'page'
            items_per_page_parameter_name: 'itemsPerPage'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        strict_email: true
        enable_annotations: true
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            AppBundle:
                type: yml
                dir: Resources/config/doctrine

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:   ["%cors_allow_origin%"]
        allow_methods:  ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers:  ["content-type", "authorization"]
        expose_headers: ["link"]
        max_age:        3600
    paths:
        '^/': ~

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Utilisateur

lexik_jwt_authentication:
    private_key_path: "%jwt_private_key_path%"
    public_key_path: "%jwt_public_key_path%"
    pass_phrase: "%jwt_key_pass_phrase%"
    token_ttl: "%jwt_token_ttl%"

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        membre_photo:
            uri_prefix: /membres/photos
            upload_destination: '%kernel.root_dir%/../web/uploads/membres/photos'
            namer: vich_uploader.namer_uniqid

# RabbbitMQ
old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbitmq_host%'
            port: '%rabbitmq_port%'
            user: '%rabbitmq_user%'
            password: '%rabbitmq_pass%'
            vhost: '/'
            lazy: true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false  # requires php-amqplib v2.4.1+ and PHP5.4+
            heartbeat: 0      # requires php-amqplib v2.4.1+
            use_socket: true  # default false #requires php_sockets.dll
    producers:
        send_solution:
            connection: default
            queue_options:
                name: 'submit-solutions'
            exchange_options:
                name: 'submit-solutions'
                type: 'direct'
            service_alias: app.solution_producer