api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

api_login_check:
    path: /api/login_check

membre_upload_photo:
    path: 'membres/{id}/photo'
    methods: ['POST']
    defaults:
        _controller: 'AppBundle\Action\Membre\UploadPhoto'

organisateur_get_competitions:
    path: 'organisateurs/{id}/competitions'
    methods: ['GET']
    defaults:
        _parent_entity: 'AppBundle:Organisateur'
        _api_resource_class: 'AppBundle\Entity\Competition'
        _api_item_operation_name: 'get_competitions'
        _controller: 'AppBundle\Action\GetSubResourcesAction'

pays_get_villes:
    path: 'pays/{id}/villes'
    methods: ['GET']
    defaults:
        _parent_entity: 'AppBundle:Pays'
        _api_resource_class: 'AppBundle\Entity\Ville'
        _api_item_operation_name: 'get_villes'
        _controller: 'AppBundle\Action\GetSubResourcesAction'

participant_get_solutions:
    path: 'participants/{id}/solutions'
    methods: ['GET']
    defaults:
        _parent_entity: 'AppBundle:Participant'
        _api_resource_class: 'AppBundle\Entity\Solution'
        _api_item_operation_name: 'get_solutions'
        _controller: 'AppBundle\Action\GetSubResourcesAction'

participant_get_invit_pariticipations:
    path: 'participants/{id}/invit_participations'
    methods: ['GET']
    defaults:
        _parent_entity: 'AppBundle:Participant'
        _api_resource_class: 'AppBundle\Entity\InvitParticipation'
        _api_item_operation_name: 'get_invit_pariticipations'
        _controller: 'AppBundle\Action\GetSubResourcesAction'
        
participant_get_demande_pariticipations:
    path: 'participants/{id}/demande_participations'
    methods: ['GET']
    defaults:
        _parent_entity: 'AppBundle:Participant'
        _api_resource_class: 'AppBundle\Entity\DemandeParticipation'
        _api_item_operation_name: 'get_demande_pariticipations'
        _controller: 'AppBundle\Action\GetSubResourcesAction'

membre_get:
    path: 'membres/{id}'
    methods: ['GET']
    defaults:
        _api_resource_class: 'AppBundle\Entity\Membre'
        _api_item_operation_name: 'membre_get'
        _controller: 'AppBundle\Action\Membre\Get'