# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    competition.search_filter:
        parent:    'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { public: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'competition.public' } ]
