
AppBundle\Entity\Pays: ~
AppBundle\Entity\FichierCode: ~
AppBundle\Entity\Solution: ~

AppBundle\Entity\EntreeSortie:
    attributes:
        entree:
            groups: [es-read, write]
        sortie:
            groups: [es-read, write]
        type:
            groups: [es-read, write]
        probleme:
            groups: [es-read, write]

AppBundle\Entity\TypeEntreeSortie:
    attributes:
        name:
            groups: [type-es-read, write]

AppBundle\Entity\Probleme:
    attributes:
        enonce:
            groups: [prob-read, write]
        competition:
            groups: [prob-read, write]
        solutions:
            groups: [prob-read, write]
        titre:
            groups: [prob-read, write]
        entreeSorties:
            groups: [prob-read, write]

AppBundle\Entity\TypeParticipation:
    attributes:
        nom:
            groups: [type-particip-read, brief]

AppBundle\Entity\Participation:
    attributes:
        accepte:
            groups: [particip-read, write]
        dateTime:
            groups: [particip-read]
        competition:
            groups: [particip-read, write]
        participant:
            groups: [particip-read, write]
        type:
            groups: [particip-read, write]

AppBundle\Entity\Utilisateur:
    attributes:
        username:         
            groups: [read, write] 
        email:         
            groups: [read, write, invit-read]
        plainPassword:
            groups: [write]

AppBundle\Entity\Organisateur:
    attributes:
        nom:         
            groups: [read, write, brief] 

AppBundle\Entity\Membre:
    attributes:
        ville:         
            groups: [read, write] 
        presentation:         
            groups: [read, write] 
        cheminPhoto:         
            groups: [read] 
        telephone:         
            groups: [read, write] 
        adresse:         
            groups: [read, write] 
        siteWeb:         
            groups: [read, write] 

AppBundle\Entity\Competition:
    attributes:
        description:
            groups: [comp-read, write]
        demandeParticipations:         
            groups: [comp-read]
        invitParticipations:         
            groups: [comp-read] 
        organisateur:         
            groups: [comp-read, write] 
        problemes:
            groups: [comp-read]
        langages:
            groups: [comp-read] 
        titre:
            groups: [comp-read, write]
        tempsDebut:
            groups: [comp-read, write]
        tempsFin:
            groups: [comp-read, write]
        public:
            groups: [comp-read, write]
        publie:
            groups: [comp-read, write]

AppBundle\Entity\Langage:
    attributes:
        nom:
            groups: [read, write, brief]

AppBundle\Entity\Ville:
    attributes:
        pays:         
            groups: [read, write] 
        nom:         
            groups: [read, write] 

AppBundle\Entity\Participant:
    attributes:
        prenom:         
            groups: [read, write, invit-read, brief] 
        nom:         
            groups: [read, write, invit-read, brief] 
        job:         
            groups: [read, write]
