AppBundle\Entity\FichierCode:
    properties:
        contenu:
            - Required: ~

AppBundle\Entity\Solution:
    properties:
        fichiersCode:
            - Valid: ~
            #- Count: { min: 1 }
