AppBundle\Entity\FichierCode:
    properties:
        contenu:
            - Required: ~

AppBundle\Entity\Solution:
    properties:
        participant:
            - NotNull: ~
        langage:
            - NotNull: ~
        probleme:
            - NotNull: ~
        fichierZip:
            - NotNull: ~
        #fichiersCode:
        #    - Valid: ~
            #- Count: { min: 1 }
