AppBundle\Entity\Competition:
    type: entity
    repositoryClass: AppBundle\Repository\CompetitionRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            length: 255
            nullable: false
        description:
            type: text
            nullable: false
        tempsDebut:
            type: datetime
            nullable: false
            column: temps_debut
        tempsFin:
            type: datetime
            nullable: false
            column: temps_fin
        public:
            type: boolean
            nullable: false
        publie:
            type: boolean
            nullable: false
    oneToMany:
        problemes:
            targetEntity: AppBundle\Entity\Probleme
            cascade:
                - persist
            mappedBy: competition
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        participations:
            targetEntity: AppBundle\Entity\Participation
            cascade:
                - persist
            mappedBy: competition
    manyToMany:
        langages:
            targetEntity: AppBundle\Entity\Langage
            mappedBy: competitions
            cascade:
                - persist
    manyToOne:
        organisateur:
            targetEntity: AppBundle\Entity\Organisateur
            cascade: {  }
            inversedBy: competitions
            joinColumns:
                organisateur_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
