AppBundle\Entity\DemandeParticipation:
    type: entity
    table: demande_participation
    repositoryClass: AppBundle\Repository\DemandeParticipationRepository
    uniqueConstraints:
        -
            columns:
                - participant_id
                - competition_id
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accepte:
            type: boolean
            nullable: true
        date:
            type: datetime
            nullable: false
    manyToOne:
        competition:
            targetEntity: AppBundle\Entity\Competition
            cascade:
                - persist
            inversedBy: demandeParticipations
            joinColumns:
                competition_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        participant:
            targetEntity: AppBundle\Entity\Participant
            cascade:
                - persist
            inversedBy: demandeParticipations
            joinColumns:
                participant_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
