AppBundle\Entity\EntreeSortie:
    type: entity
    repositoryClass: AppBundle\Repository\EntreeSortieRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entree:
            type: text
            nullable: false
        sortie:
            type: text
            nullable: false
    manyToOne:
        type:
            targetEntity: AppBundle\Entity\TypeEntreeSortie
            cascade: {  }
            inversedBy: enteeSorties
            joinColumns:
                type_id:
                    nullable: false
            orphanRemoval: false
        probleme:
            targetEntity: AppBundle\Entity\Probleme
            inversedBy: entreeSorties
            cascade:
                - persist
#            joinColumns:
#                probleme_id:
#                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
