AppBundle\Entity\FichierCode:
    type: entity
    table: fichier_code
    repositoryClass: AppBundle\Repository\FichierCodeRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contenu:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        solution:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: fichiersCode
            joinColumns:
                solution_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
