AppBundle\Entity\FichierCode:
    type: entity
    repositoryClass: AppBundle\Repository\FichierCodeRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contenu:
            type: text
            nullable: false
    manyToOne:
        solution:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            inversedBy: fichiersCode
            joinColumns:
                solution_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
