AppBundle\Entity\InvitParticipation:
    type: entity
    table: invit_participation
    repositoryClass: AppBundle\Repository\InvitParticipationRepository
    uniqueConstraints:
        -
            columns:
                - participant_id
                - competition_id
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accepte:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        dateTime:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: date_time
    manyToOne:
        competition:
            targetEntity: AppBundle\Entity\Competition
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: invitParticipations
            joinColumns:
                competition_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        participant:
            targetEntity: AppBundle\Entity\Participant
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: invitParticipations
            joinColumns:
                participant_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
