AppBundle\Entity\InvitParticipation:
    type: entity
    table: invit_participation
    repositoryClass: AppBundle\Repository\InvitParticipationRepository
    uniqueConstraints:
        -
            columns:
                - participant_id
                - competition_id
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accepte:
            type: boolean
            nullable: true
        dateTime:
            type: datetime
            nullable: false
            column: date_time
    manyToOne:
        competition:
            targetEntity: AppBundle\Entity\Competition
            cascade: {  }
            inversedBy: invitParticipations
            joinColumns:
                competition_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        participant:
            targetEntity: AppBundle\Entity\Participant
            cascade:
                - persist
            inversedBy: invitParticipations
            joinColumns:
                participant_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
