AppBundle\Entity\Langage:
    type: entity
    repositoryClass: AppBundle\Repository\LangageRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            length: 255
            unique: true
            nullable: false
    oneToMany:
        solutions:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            mappedBy: langage
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    manyToMany:
        competitions:
            targetEntity: AppBundle\Entity\Competition
            cascade:
                - persist
            inversedBy: langages
            orderBy: null
    lifecycleCallbacks: {  }
