AppBundle\Entity\Organisateur:
    type: entity
    table: organisateur
    repositoryClass: AppBundle\Repository\OrganiserRepository
    fields:
        nom:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
    oneToMany:
        competitions:
            targetEntity: AppBundle\Entity\Competition
            cascade:
                - persist
            fetch: LAZY
            mappedBy: organisateur
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
