AppBundle\Entity\Participant:
    type: entity
    table: participant
    repositoryClass: AppBundle\Repository\ParticipantRepository
    fields:
        prenom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        nom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        job:
            type: string
            scale: 0
            length: 30
            unique: false
            nullable: true
            precision: 0
    oneToMany:
        solutions:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            fetch: LAZY
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        invitParticipations:
            targetEntity: AppBundle\Entity\InvitParticipation
            cascade:
                - persist
            fetch: LAZY
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        demandeParticipations:
            targetEntity: AppBundle\Entity\DemandeParticipation
            cascade:
                - persist
            fetch: LAZY
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
