AppBundle\Entity\Participation:
    type: entity
    repositoryClass: AppBundle\Repository\ParticipationRepository
    uniqueConstraints:
        - columns:
            - participant_id
            - competition_id
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accepte:
            type: boolean
            nullable: true
        dateTime:
            type: datetime
            nullable: false
            column: date_time
    manyToOne:
        type:
            targetEntity: AppBundle\Entity\TypeParticipation
            inversedBy: participations
            joinColumns:
                type_id:
                    onDelete: CASCADE
                    nullable: false
        competition:
            targetEntity: AppBundle\Entity\Competition
            cascade: {  }
            inversedBy: participations
            joinColumns:
                competition_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        participant:
            targetEntity: AppBundle\Entity\Participant
            cascade:
                - persist
            inversedBy: participations
            joinColumns:
                participant_id:
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
