AppBundle\Entity\Participant:
    type: entity
    repositoryClass: AppBundle\Repository\ParticipantRepository
    fields:
        prenom:
            type: string
            length: 255
            nullable: false
        nom:
            type: string
            length: 255
            nullable: false
        job:
            type: string
            length: 30
            nullable: true
    oneToMany:
        solutions:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        participations:
            targetEntity: AppBundle\Entity\Participation
            cascade:
                - persist
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
