AppBundle\Entity\Participant:
    type: entity
    table: participant
    repositoryClass: AppBundle\Repository\ParticipantRepository
    fields:
        prenom:
            type: string
            length: 255
            nullable: false
        nom:
            type: string
            length: 255
            nullable: false
        job:
            type: string
            length: 30
            nullable: true
    oneToMany:
        solutions:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        invitParticipations:
            targetEntity: AppBundle\Entity\InvitParticipation
            cascade:
                - persist
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        demandeParticipations:
            targetEntity: AppBundle\Entity\DemandeParticipation
            cascade:
                - persist
            mappedBy: participant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
