AppBundle\Entity\Pays:
    type: entity
    table: pays
    repositoryClass: AppBundle\Repository\PaysRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            length: 255
            unique: true
            nullable: false
    oneToMany:
        villes:
            targetEntity: AppBundle\Entity\Ville
            cascade: {  }
            mappedBy: pays
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
