AppBundle\Entity\Probleme:
    type: entity
    repositoryClass: AppBundle\Repository\ProblemeRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        enonce:
            type: text
            nullable: false
        titre:
            type: string
            length: 255
            nullable: false
    manyToOne:
        competition:
            targetEntity: AppBundle\Entity\Competition
            cascade: {  }
            inversedBy: problemes
            joinColumns:
                competition_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
    oneToMany:
        solutions:
            targetEntity: AppBundle\Entity\Solution
            cascade:
                - persist
            mappedBy: probleme
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        entreeSorties:
            targetEntity: AppBundle\Entity\EntreeSortie
            cascade:
                - persist
            mappedBy: probleme
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
