AppBundle\Entity\Solution:
    type: entity
    table: solution
    repositoryClass: AppBundle\Repository\SolutionRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tempsEnvoie:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        tempsExécution:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        correcte:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    oneToMany:
        fichiersCode:
            targetEntity: AppBundle\Entity\FichierCode
            cascade:
                - persist
            fetch: LAZY
            mappedBy: solution
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    manyToOne:
        participant:
            targetEntity: AppBundle\Entity\Participant
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: solutions
            joinColumns:
                participant_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
        langage:
            targetEntity: AppBundle\Entity\Langage
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: solutions
            joinColumns:
                langage_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
        probleme:
            targetEntity: AppBundle\Entity\Probleme
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: solutions
            joinColumns:
                probleme_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
