AppBundle\Entity\TypeEntreeSortie:
    type: entity
    repositoryClass: AppBundle\Repository\TypeEntreeSortieRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 30
            unique: true
            nullable: false
    lifecycleCallbacks: {  }
