AppBundle\Entity\Utilisateur:
    type: entity
    table: utilisateur
    inheritanceType: JOINED
    discriminatorColumn:
        name: _type
        type: string
        columnDefinition: null
        fieldName: _type
    discriminatorMap:
        utilisateur: AppBundle\Entity\Utilisateur
        membre: AppBundle\Entity\Membre
        organisateur: AppBundle\Entity\Organisateur
        admin: AppBundle\Entity\Admin
        participant: AppBundle\Entity\Participant
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
