AppBundle\Entity\Ville:
    type: entity
    table: ville
    repositoryClass: AppBundle\Repository\VilleRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
    manyToOne:
        pays:
            targetEntity: AppBundle\Entity\Pays
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: villes
            joinColumns:
                pays_id:
                    nullable: false
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
